modLoader="javafml"
loaderVersion="[40,)"
license="LGPL v2.1"
[[mods]]
modId="loadingprofiler"
version="${file.jarVersion}" #mandatory
displayName="Loading Profiler" #mandatory
logoFile="loadingprofiler.png" #optional
credits="Thanks lcy0x1" #optional
authors="lcy0x1 and LightLand team" #optional
description='''
A profiler mod that profide statistics on game start up
'''
[[dependencies.loadingprofiler]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.loadingprofiler]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"